// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  embed: dynamic(() => import("./Embed")),
  split_image: dynamic(() => import("./SplitImage")),
  text_slice: dynamic(() => import("./TextSlice")),
};
